mapping:
  perform_mapping: False, # should splicekit perform mapping of reads from FASTQ to the reference genome with pybio? (True=yes, False=no)
  alignIntronMax: 5000   # leave at None or set a number [nt], e.g.: 5000

defaults:
  cores: 1
  mem: 4            # GB
  time: "01:00:00"  # hours

map_fastq_single:
  cores: 8
  mem: 8            # GB
  time: "02:00:00"  # hours

map_fastq_paired:
  cores: 8
  mem: 8            # GB
  time: "02:00:00"  # hours

bam_index:
  cores: 8
  mem: 2            # GB
  time: "02:00:00"  # hours

bam_bw:
  cores: 8
  mem: 2            # GB
  time: "02:00:00"  # hours

feature_counts:
  cores: 8
  mem: 2            # GB
  time: "01:00:00"  # hours

edgeR:
  cores: 1
  mem: 4            # GB
  time: "04:00:00"  # hours

edgeR_assemble:
  cores: 1
  mem: 16           # GB
  time: "04:00:00"  # hours

juan:
  cores: 1
  mem: 16           # GB
  time: "01:00:00"  # hours
